apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadywwe9425-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadywwe9425-tenant-component
    app.kubernetes.io/part-of: loadywwe9425-tenant-app
  name: loadywwe9425-tenant-component
  namespace: loadywwe9425-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadywwe9425-tenant-component
    weight: null
status: {}
